services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    hostname: gitea.local
    ports:
      - "3000:3000"   # Port Web de Gitea
      - "22:22"       # Port SSH pour les dépôts Git
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__security__INSTALL_LOCK=true      # Verrouillage de l'installation
      - GITEA__database__DB_TYPE=sqlite3       # Type de base de données (ici SQLite)
      - GITEA__database__DB_PATH=/data/gitea/gitea.db  # Chemin de la base de données
      - GITEA__security__ADMIN_PASSWORD=rootpassword # Mot de passe pour l'administrateur
      - GITEA__security__ADMIN_USER=admin      # Utilisateur administrateur
      - GITEA__server__DOMAIN=gitea.local     # Domaine de Gitea
      - GITEA__server__ROOT_URL=http://gitea.local  # URL racine pour Gitea
    volumes:
      - gitea-data:/data
      - gitea-logs:/var/log/gitea
      - gitea-config:/etc/gitea
  
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
  gitea-data:
  gitea-logs:
  gitea-config:

